version: "3.8"
services:

  # PHP service
  app:
    build: .
    container_name: php-app
    working_dir: /var/www/proxy-checker
    restart: always
    volumes:
      - ./:/var/www/proxy-checker
    networks:
      - app-network

  # MySQL database service
  db:
    image: mariadb:10.5.8
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app-network

  # adminer service
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: php-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/proxy-checker
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: ~
  db-data-ch: ~
